kind: pipeline
name: default

#forcepush

steps:
- name: publish
  image: plugins/docker
  dockerfile: Dockerfile
  settings: 
    registry: registry.mrcow.xyz
    repo: registry.mrcow.xyz/cow/react-leaderboard
    tags: latest
    use_cache: true
    cache_from: "registry.mrcow.xyz/cow/react-leaderboard:latest"
  when:
    branch: 
      - master